apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-server
  labels:
    app: express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express-server
        image: emil/express-server
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: express-server-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000