apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-server
  labels:
    app: express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express-server
        image: emil/express-server:1.0.1
        imagePullPolicy: Never
        env:
          - name: NODE_CONFIG_ENV
            value: "production"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: express-server-service
spec:
  selector:
    app: express
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000